### ISSUE TITLE
Data por extenso?

### ISSUE THREAD

**Issue by edusantana** [portujs/extenso.js#37]
Tem interesse em implementar data por extenso?

Ou de aceitar implementação?

**Comment by theuves** [comment]
Olá, @edusantana!

O foco principal da biblioteca é ter números como *input*, mas acho a ideia de datas interessante. Talvez caiba fazê-lo em uma nova biblioteca, o que você acha disso?

**Comment by edusantana** [comment]
A motivação era facilitar elaboração de [filtro liquidjs](https://liquidjs.com/tutorials/intro-to-liquid.html):

```javascript
import pkg from 'liquidjs';
const { Liquid } = pkg;
import extenso from 'extenso';

const engine = new Liquid();

// inicio da definição do filtro
engine.registerFilter('por_extenso', (str, modificador) => {
  let opcoes = {}

  if (modificador === "f") {
      opcoes["number"] = { gender: 'f' }
  }else if(modificador === "$"){
      opcoes = {mode: 'currency', currency: { type: 'BRL' } }
  }
  
  return extenso(str, opcoes)
}) // fim do filtro

// exemplo de utilização do filtro
let texto = "Tome a cada {{ horas }} ({{ horas | por_extenso: \"f\"}}) horas durante {{ dias }} ({{ dias | por_extenso}}) dias. Ele custa R$ {{custo}} ({{ custo | por_extenso: '$'}}). {{ hoje }}"

console.log("modelo:" + texto)

engine
    .parseAndRender(texto, {horas: '2', dias: '2', custo: "1,99", hoje: new Date()})
    .then(console.log);
```

Para data seria utilizando [luxon](https://moment.github.io/luxon/):

```javascript
var { DateTime } = require('luxon');
DateTime.local().toLocaleString(DateTime.DATE_FULL)
// '28 de outubro de 2020'
```

Juntando isso daí daria para fazer um filtro liquidjs bem simples: `{{valor | por_extenso}}`

**Comment by theuves** [comment]
Pelo que entendi isso daria um log de algo como:

```js
Tome a cada 2 (duas) horas durante 2 (dois) dias. Ele custa R$ 1,99 (um real e noventa e nova centavos).
```

Até aqui tudo normal.

No entanto, no exemplo com luxon temos um output parcialmente por extenso.

Você planeja algo como nos exemplos abaixo?

```
extenso(1605147925643, { mode: 'date', ... })
//=> '11 de novembro de 2020'

// ou...

//=> 'onze de novembro de dois mil e vinte'
```

**Comment by theuves** [comment]
Se for somente pela questão como no luxon (para retorno de '11 de novembro de 2020`) o próprio JavaScript pode realizar a tarefa sem grandes problemas.

Experimente os trechos abaixo:

```javascript
let date = new Date(1605147925643)

date.toLocaleDateString('pt-BR', { dateStyle: 'full' })
//=> 'quarta-feira, 11 de novembro de 2020'

date.toLocaleDateString('pt-BR', { dateStyle: 'long' })
//=> '11 de novembro de 2020'

date.toLocaleDateString('pt-BR', { dateStyle: 'medium' })
//=> '11 de nov. de 2020'
```

Veja mais informações sobre o método `.toLocaleDateString()` na [w3schools](https://www.w3schools.com/jsref/jsref_tolocalestring.asp) ou na [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString).

**Comment by theuves** [comment]
Mil perdões caso eu tenha compreendido errado. Caso sua ideia não seja essa que eu apresentei acima, por favor, apresente alguns exemplos semelhantes de como você o idealiza.

Por exemplo:

```javascript
extenso(x, {y: z}) //=> 'foo bar'
```

De qualquer modo, acredito que seja interessante ter outra biblioteca para solucionar o caso, visto que o Extenso.js trabalha principalmente com números simples como input.

**Comment by edusantana** [comment]
@theuves Obrigado! Esta extensão polpa trabalho.

**Comment by theuves** [comment]
Muito bom @edusantana!

Qualquer descoberta ou ideia sinta-se livre para compartilhar conosco.

Vou fechar essa *issue*, mas podemos abri-la novamente se ainda necessário.
