### ISSUE TITLE
Erro em valor monetário acima de 1 milhão

### ISSUE THREAD

**Issue by renatoasse** [portujs/extenso.js#38]
Olá, ocorre um erro na formatação do número extenso quando tento puxar um valor monetário acima de 1 milhão de reais:

![image](https://user-images.githubusercontent.com/47402948/101214697-2bd16880-365b-11eb-84c9-280c726d814e.png)

**Comment by theuves** [comment]
Oi, @renatoasse!

Estaremos verificando esse comportamento.

**Comment by theuves** [comment]
Corrigido no PR #49 pelo @GuiDevloper . Em breve vou publicar a nova versão no NPM.
