### ISSUE TITLE
Esse repo ainda é ativo?

### ISSUE THREAD

**Issue by Krymancer** [portujs/extenso.js#59]
Conheci o projeto por conta [um tweet](https://twitter.com/igorhalfeld/status/1690546819397283840) e resolvi dar uma olhada, notei que tem algumas issues em aberto, mas não parece que tem muito desenvolvimento, acredito que seria interessaste adicionar tipos utilizando typscript ou js doc.

**Comment by theuves** [comment]
Olá, Junior.

Me distanciei do desenvolvimento web por alguns anos então quase todos meus projetos open-source ficaram desatualizados.

Estou voltando agora e pretendo lançar uma nova versão em breve com correções e atualizações.
